### ISSUE TITLE
false positive with any uribl

### ISSUE THREAD

**Issue by deepvoice** [dmippolitov/pydnsbl#23] opened 2022-04-15 20:27 UTC
multi.uribl.com
Using: 
example1.com (no listing)
example.com (whitelisted)

'blacklisted': True, 'detectedBY': {'multi.uribl.com': ['unknown']}, 'notation': <DNSBLResult: example1.com [BLACKLISTED] (1/58)>}

and if "Whitelisted" same:
'blacklisted': True, 'detectedBY': {'multi.uribl.com': ['unknown']}, 'notation': <DNSBLResult: example.com [BLACKLISTED] (1/58)>}

**Comment by dmippolitov** [comment] 2022-05-09 17:54
Hi, could you provide me a snippet of code where you get this?

**Comment by TAnas0** [comment] 2022-09-23 01:06
I believe that what the original post is referring to is false positive on all inputs:

```bash
Python 3.9.12 (main, Apr 18 2022, 22:40:46) 
[GCC 9.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import pydnsbl
>>> ip_checker = pydnsbl.DNSBLIpChecker()
>>> ip_checker.check('8.8.8.8')
<DNSBLResult: 8.8.8.8 [BLACKLISTED] (1/50)>
>>> ip_checker.check('68.128.212.240')
<DNSBLResult: 68.128.212.240 [BLACKLISTED] (6/50)>
>>> domain_checker = pydnsbl.DNSBLDomainChecker()
>>> domain_checker.check('google.com')
<DNSBLResult: google.com [BLACKLISTED] (1/4)>
>>> 
```

**Comment by dmippolitov** [comment] 2023-10-17 10:07
Cant reproduce this, possibly some temporary problems. Closing.

**Closed as completed by dmippolitov** 2023-10-17 10:07 UTC
